[project]
name = "desi-selection-exploration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fitsio>=1.4.2",
    "ipympl>=0.10.0",
    "jupyterlab>=4.6.3",
    "matplotlib>=3.11.1",
    "numpy==1.26",
    "sparclclient>=1.3.0",
    "specutils>=2.4.0",
]
